package com.yenusoft.revelation;

import android.Manifest;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.os.Handler;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.Toast;

import com.yenusoft.revelation.Dictionary.Chapter;
import com.yenusoft.revelation.Dictionary.Verse;
import com.yenusoft.revelation.Lobby.Lobby;
import com.yenusoft.revelation.Lobby.WrongNote;

public class Logo extends AppCompatActivity
{
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.logo);

        final Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                fcSetDict();
                fcSetRevMaxVerse();
                funcCheckPermission(Logo.this);

            }
        }, 1000);
    }

    private void fcSetDict()
    {
        Dict.dict = new Dict();
        Chapter c = new Chapter(1, getString(R.string.revelation), getString(R.string.revel));
        Verse v = new Verse(1, getString(R.string.revelation_1_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_1_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_1_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_1_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_1_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_1_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_1_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_1_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_1_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_1_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_1_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_1_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_1_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_1_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_1_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_1_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_1_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_1_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_1_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_1_20));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(2, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_2_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_2_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_2_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_2_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_2_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_2_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_2_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_2_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_2_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_2_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_2_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_2_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_2_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_2_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_2_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_2_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_2_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_2_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_2_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_2_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_2_21));
        c.getVers().add(v);
        v = new Verse(22, getString(R.string.revelation_2_22));
        c.getVers().add(v);
        v = new Verse(23, getString(R.string.revelation_2_23));
        c.getVers().add(v);
        v = new Verse(24, getString(R.string.revelation_2_24));
        c.getVers().add(v);
        v = new Verse(25, getString(R.string.revelation_2_25));
        c.getVers().add(v);
        v = new Verse(26, getString(R.string.revelation_2_26));
        c.getVers().add(v);
        v = new Verse(27, getString(R.string.revelation_2_27));
        c.getVers().add(v);
        v = new Verse(28, getString(R.string.revelation_2_28));
        c.getVers().add(v);
        v = new Verse(29, getString(R.string.revelation_2_29));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(3, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_3_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_3_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_3_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_3_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_3_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_3_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_3_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_3_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_3_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_3_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_3_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_3_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_3_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_3_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_3_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_3_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_3_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_3_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_3_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_3_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_3_21));
        c.getVers().add(v);
        v = new Verse(22, getString(R.string.revelation_3_22));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(4, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_4_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_4_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_4_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_4_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_4_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_4_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_4_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_4_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_4_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_4_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_4_11));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(5, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_5_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_5_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_5_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_5_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_5_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_5_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_5_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_5_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_5_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_5_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_5_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_5_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_5_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_5_14));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(6, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_6_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_6_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_6_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_6_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_6_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_6_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_6_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_6_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_6_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_6_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_6_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_6_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_6_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_6_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_6_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_6_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_6_17));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(7, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_7_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_7_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_7_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_7_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_7_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_7_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_7_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_7_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_7_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_7_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_7_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_7_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_7_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_7_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_7_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_7_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_7_17));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(8, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_8_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_8_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_8_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_8_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_8_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_8_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_8_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_8_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_8_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_8_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_8_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_8_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_8_13));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(9, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_9_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_9_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_9_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_9_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_9_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_9_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_9_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_9_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_9_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_9_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_9_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_9_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_9_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_9_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_9_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_9_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_9_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_9_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_9_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_9_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_9_21));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(10, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_10_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_10_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_10_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_10_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_10_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_10_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_10_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_10_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_10_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_10_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_10_11));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(11, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_11_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_11_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_11_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_11_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_11_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_11_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_11_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_11_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_11_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_11_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_11_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_11_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_11_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_11_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_11_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_11_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_11_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_11_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_11_19));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(12, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_12_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_12_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_12_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_12_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_12_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_12_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_12_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_12_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_12_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_12_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_12_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_12_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_12_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_12_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_12_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_12_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_12_17));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(13, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_13_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_13_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_13_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_13_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_13_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_13_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_13_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_13_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_13_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_13_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_13_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_13_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_13_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_13_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_13_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_13_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_13_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_13_18));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(14, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_14_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_14_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_14_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_14_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_14_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_14_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_14_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_14_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_14_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_14_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_14_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_14_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_14_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_14_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_14_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_14_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_14_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_14_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_14_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_14_20));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(15, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_15_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_15_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_15_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_15_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_15_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_15_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_15_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_15_8));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(16, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_16_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_16_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_16_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_16_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_16_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_16_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_16_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_16_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_16_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_16_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_16_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_16_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_16_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_16_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_16_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_16_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_16_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_16_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_16_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_16_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_16_21));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(17, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_17_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_17_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_17_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_17_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_17_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_17_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_17_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_17_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_17_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_17_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_17_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_17_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_17_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_17_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_17_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_17_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_17_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_17_18));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(18, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_18_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_18_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_18_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_18_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_18_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_18_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_18_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_18_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_18_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_18_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_18_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_18_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_18_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_18_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_18_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_18_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_18_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_18_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_18_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_18_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_18_21));
        c.getVers().add(v);
        v = new Verse(22, getString(R.string.revelation_18_22));
        c.getVers().add(v);
        v = new Verse(23, getString(R.string.revelation_18_23));
        c.getVers().add(v);
        v = new Verse(24, getString(R.string.revelation_18_24));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);


        c = new Chapter(19, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_19_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_19_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_19_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_19_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_19_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_19_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_19_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_19_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_19_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_19_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_19_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_19_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_19_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_19_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_19_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_19_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_19_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_19_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_19_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_19_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_19_21));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(20, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_20_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_20_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_20_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_20_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_20_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_20_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_20_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_20_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_20_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_20_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_20_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_20_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_20_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_20_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_20_15));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(21, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_21_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_21_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_21_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_21_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_21_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_21_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_21_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_21_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_21_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_21_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_21_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_21_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_21_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_21_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_21_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_21_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_21_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_21_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_21_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_21_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_21_21));
        c.getVers().add(v);
        v = new Verse(22, getString(R.string.revelation_21_22));
        c.getVers().add(v);
        v = new Verse(23, getString(R.string.revelation_21_23));
        c.getVers().add(v);
        v = new Verse(24, getString(R.string.revelation_21_24));
        c.getVers().add(v);
        v = new Verse(25, getString(R.string.revelation_21_25));
        c.getVers().add(v);
        v = new Verse(26, getString(R.string.revelation_21_26));
        c.getVers().add(v);
        v = new Verse(27, getString(R.string.revelation_21_27));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

        c = new Chapter(22, getString(R.string.revelation), getString(R.string.revel));
        v = new Verse(1, getString(R.string.revelation_22_1));
        c.getVers().add(v);
        v = new Verse(2, getString(R.string.revelation_22_2));
        c.getVers().add(v);
        v = new Verse(3, getString(R.string.revelation_22_3));
        c.getVers().add(v);
        v = new Verse(4, getString(R.string.revelation_22_4));
        c.getVers().add(v);
        v = new Verse(5, getString(R.string.revelation_22_5));
        c.getVers().add(v);
        v = new Verse(6, getString(R.string.revelation_22_6));
        c.getVers().add(v);
        v = new Verse(7, getString(R.string.revelation_22_7));
        c.getVers().add(v);
        v = new Verse(8, getString(R.string.revelation_22_8));
        c.getVers().add(v);
        v = new Verse(9, getString(R.string.revelation_22_9));
        c.getVers().add(v);
        v = new Verse(10, getString(R.string.revelation_22_10));
        c.getVers().add(v);
        v = new Verse(11, getString(R.string.revelation_22_11));
        c.getVers().add(v);
        v = new Verse(12, getString(R.string.revelation_22_12));
        c.getVers().add(v);
        v = new Verse(13, getString(R.string.revelation_22_13));
        c.getVers().add(v);
        v = new Verse(14, getString(R.string.revelation_22_14));
        c.getVers().add(v);
        v = new Verse(15, getString(R.string.revelation_22_15));
        c.getVers().add(v);
        v = new Verse(16, getString(R.string.revelation_22_16));
        c.getVers().add(v);
        v = new Verse(17, getString(R.string.revelation_22_17));
        c.getVers().add(v);
        v = new Verse(18, getString(R.string.revelation_22_18));
        c.getVers().add(v);
        v = new Verse(19, getString(R.string.revelation_22_19));
        c.getVers().add(v);
        v = new Verse(20, getString(R.string.revelation_22_20));
        c.getVers().add(v);
        v = new Verse(21, getString(R.string.revelation_22_21));
        c.getVers().add(v);
        Dict.i().getChapters().add(c);

//        for (int i = 0; i < Dict.i().getChapters().size(); i++)
//        {
//            for (int j = 0; j < Dict.i().getChapters().get(i).getVers().size(); j++)
//            {
//                sLog.slog(getClass().getName(), Dict.i().getChapters().get(i).getVers().get(j).getContent());
//            }
//        }
    }

    private void fcSetRevMaxVerse()
    {
        int t = 0;
        for (int i = 0; i < Dict.i().getChapters().size(); i++)
            t += Dict.i().getChapters().get(i).getVers().size();

        Dict.i().setRevMaxVerse(t);
    }

    public static void fcSetWrongNote(Context mContext)
    {
        Dict.i().getWrongNotes().clear();
        myDB my = new myDB(mContext);
        Cursor row = my.funcSelect("SELECT * FROM wrong_note");

        if (row == null)
            return;

        for (int i = 0; i < row.getCount(); i++)
        {
            int id = row.getInt(row.getColumnIndex("id"));
            int abb_num = row.getInt(row.getColumnIndex("abb_num"));
            int chapter = row.getInt(row.getColumnIndex("chapter"));
            int verse = row.getInt(row.getColumnIndex("verse"));
            int count = row.getInt(row.getColumnIndex("count"));
            WrongNote wn = new WrongNote(id, abb_num, chapter, verse, count);
            Dict.i().getWrongNotes().add(wn);

            row.moveToNext();
        }

//        for (int i = 0; i < Dict.i().getWrongNotes().size(); i++)
//        {
//            sLog.slog(getClass().getName(), Dict.i().getWrongNotes().get(i).getChapter());
//            sLog.slog(getClass().getName(), Dict.i().getWrongNotes().get(i).getVerse());
//        }
    }

    private void fcGoLobby()
    {
        Intent i = new Intent(Logo.this, Lobby.class);
        startActivity(i);
        finish();
    }

    public void funcCheckPermission(Context context)
    {
        if (ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) //권한이 없을 경우
        {
            if (ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)) //화면에 뛰움
                Toast.makeText(this, R.string.alert_allow, Toast.LENGTH_SHORT).show();

            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 0);
        }
        else //6.0 미만
        {
            fcSetWrongNote(Logo.this);
            fcGoLobby();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
    {
        if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            fcSetWrongNote(Logo.this);
            fcGoLobby();
        }
        else {
            Toast.makeText(this, R.string.alert_deny, Toast.LENGTH_SHORT).show();
            finish();
        }
    }
}
